services:
  python_compiler:
    build:
      context: .
      dockerfile: docker/code_compiler/Dockerfile
    container_name: python_compiler
    image: python_compiler
    restart: always
    env_file:
      - .env
    command: sh -c "python3 consumer.py"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
      image: postgres:13.7-alpine3.15
      restart: always
      container_name: compiler_postgres
      environment:
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        PGPORT : ${PGPORT}
        PGDATA: ${PGDATA}
      volumes:
        - "./db_data:/var/lib/postgresql/data"
      ports:
        - "5434:5434"
      healthcheck:
        test:
          [
            "CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"
          ]
        interval: 10s
        timeout: 20s
        retries: 20

  redis:
    image: "redis"
    container_name: compiler_redis
    restart: always
    ports:
      - "6379:6379"
